=== MartinGalik/survey/src/xml/response.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!--/////////////////////// definition of simple elements ////////////////////////-->
    <xsd:element name="answerId"        type="xsd:nonNegativeInteger"/>
    <xsd:element name="questionId"      type="xsd:nonNegativeInteger"/>
    <xsd:element name="surveyId"        type="xsd:nonNegativeInteger"/>


    <!--/////////////////////// definition of simple types ///////////////////////////-->
    <xsd:simpleType name="nonEmptyStringType">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!--/////////////////////// definition of complex elements ///////////////////////-->
    <xsd:element name="answers">
        <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="unbounded">
                <xsd:element ref="answerId"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="question">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="questionId"/>
                <xsd:element ref="answers"/>
            </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="uniqueAnswerId">
            <xsd:selector xpath=".//answerId"/>
            <xsd:field xpath="."/>
        </xsd:unique>
    </xsd:element>

    <xsd:element name="questions">
        <xsd:complexType>
            <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                <xsd:element ref="question"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="response">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="surveyId"/>
                <xsd:element ref="questions"/>
            </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="uniqueQuestionId">
            <xsd:selector xpath=".//questionId"/>
            <xsd:field xpath="."/>
        </xsd:unique>
    </xsd:element>

    <!--/////////////////////// root ///////////////////////////////////////////////////-->
    <xsd:element name="responses">
        <xsd:complexType>
            <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                <xsd:element ref="response"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== MartinGalik/survey/src/xml/response.xml
<?xml version="1.0" encoding="utf-8"?>

<!--root element-->
<responses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="response.xsd">
    <!--
        - element response represents response from respondent
        - it must contain survey ID and questions at all times
    -->
    <response>
        <!--
            - this element has the value of survey ID from survey.xml
            - only non-negative integer is permitted
        -->
        <surveyId>1</surveyId>
        <!--
            - questions is a set of questions with AT LEAST ONE selected answer
            - if there was no selected answer for question it is not present
        -->
        <questions>
            <!--
                - question element represents question with at least one selected answer
                - must contain question ID and set of answers
                - question ID is unique inside response
            -->
            <question>
                <!--
                    - this element has the value of question ID from survey.xml
                    - only non-negative integer is permitted
                -->
                <questionId>1</questionId>
                <!--
                    - answers represents set of selected answers in question
                    - must contain at least one ID
                -->
                <answers>
                    <!--
                        - this element has the value of answer ID from survey.xml
                        - only non-negative integer is permitted
                    -->
                    <answerId>1</answerId>
                </answers>
            </question>
            <question>
                <questionId>2</questionId>
                <answers>
                    <answerId>1</answerId>
                    <answerId>3</answerId>
                    <answerId>4</answerId>
                </answers>
            </question>
        </questions>
    </response>
    <response>
        <surveyId>2</surveyId>
        <questions>
            <question>
                <questionId>1</questionId>
                <answers>
                    <answerId>1</answerId>
                </answers>
            </question>
            <question>
                <questionId>2</questionId>
                <answers>
                    <answerId>3</answerId>
                </answers>
            </question>
        </questions>
    </response>
</responses>
